import type { SeafoodItem, Order, ProcessingStepRecord } from "./types";

export const MOCK_SEAFOOD: SeafoodItem[] = [
  {
    id: "bolong",
    name: "波士顿龙虾",
    category: "龙虾",
    emoji: "🦞",
    poolNumber: "A1",
    vitalityStatus: "alive",
    pricePerJin: 128,
    weightMin: 1.2,
    weightMax: 1.8,
    unit: "斤",
    isSoldOut: false,
    lastWaterChange: "09:30",
    isLowOxygen: false,
    description: "鲜活波龙，活力十足，钳大肉厚",
    processingMethods: [
      { id: "steam", name: "清蒸", fee: 0, estimatedMinutes: 15 },
      { id: "garlic", name: "蒜蓉", fee: 10, estimatedMinutes: 18 },
      { id: "cheese", name: "芝士焗", fee: 15, estimatedMinutes: 22 },
    ],
  },
  {
    id: "suzicrab",
    name: "梭子蟹",
    category: "螃蟹",
    emoji: "🦀",
    poolNumber: "B3",
    vitalityStatus: "alive",
    pricePerJin: 68,
    weightMin: 0.4,
    weightMax: 0.7,
    unit: "斤",
    isSoldOut: false,
    lastWaterChange: "08:45",
    isLowOxygen: false,
    description: "东海直供梭子蟹，膏满肉肥",
    processingMethods: [
      { id: "steam", name: "清蒸", fee: 0, estimatedMinutes: 12 },
      { id: "spicy", name: "椒盐", fee: 8, estimatedMinutes: 15 },
      { id: "garlic", name: "蒜蓉", fee: 8, estimatedMinutes: 15 },
    ],
  },
  {
    id: "abalone",
    name: "鲍鱼",
    category: "贝类",
    emoji: "🐚",
    poolNumber: "C2",
    vitalityStatus: "alive",
    pricePerJin: 88,
    weightMin: 0.08,
    weightMax: 0.15,
    unit: "斤/只",
    isSoldOut: false,
    lastWaterChange: "10:00",
    isLowOxygen: false,
    description: "大连鲜鲍，个头饱满，口感Q弹",
    processingMethods: [
      { id: "steam", name: "清蒸", fee: 0, estimatedMinutes: 8 },
      { id: "garlic", name: "蒜蓉", fee: 5, estimatedMinutes: 10 },
      { id: "sashimi", name: "刺身", fee: 10, estimatedMinutes: 5 },
    ],
  },
  {
    id: "grouper",
    name: "石斑鱼",
    category: "鱼类",
    emoji: "🐟",
    poolNumber: "D1",
    vitalityStatus: "alive",
    pricePerJin: 98,
    weightMin: 1.5,
    weightMax: 2.5,
    unit: "斤",
    isSoldOut: false,
    lastWaterChange: "07:30",
    isLowOxygen: false,
    description: "深海石斑，肉质细嫩，清蒸首选",
    processingMethods: [
      { id: "steam", name: "清蒸", fee: 0, estimatedMinutes: 12 },
      { id: "braise", name: "红烧", fee: 5, estimatedMinutes: 18 },
    ],
  },
  {
    id: "mantis",
    name: "皮皮虾",
    category: "虾类",
    emoji: "🦐",
    poolNumber: "E2",
    vitalityStatus: "alive",
    pricePerJin: 55,
    weightMin: 0.3,
    weightMax: 0.6,
    unit: "斤",
    isSoldOut: false,
    substituteId: "suzicrab",
    lastWaterChange: "09:15",
    isLowOxygen: false,
    description: "鲜活皮皮虾，带膏率极高",
    processingMethods: [
      { id: "steam", name: "清蒸", fee: 0, estimatedMinutes: 10 },
      { id: "spicy", name: "椒盐", fee: 8, estimatedMinutes: 12 },
      { id: "spicy_soup", name: "香辣", fee: 10, estimatedMinutes: 15 },
    ],
  },
  {
    id: "oyster",
    name: "生蚝",
    category: "贝类",
    emoji: "🦪",
    poolNumber: "C4",
    vitalityStatus: "alive",
    pricePerJin: 38,
    weightMin: 0.2,
    weightMax: 0.4,
    unit: "斤/只",
    isSoldOut: true,
    substituteId: "abalone",
    lastWaterChange: "08:00",
    isLowOxygen: false,
    description: "乳山生蚝，肥美多汁",
    processingMethods: [
      { id: "steam", name: "清蒸", fee: 0, estimatedMinutes: 8 },
      { id: "garlic", name: "蒜蓉", fee: 5, estimatedMinutes: 10 },
      { id: "sashimi", name: "生食", fee: 8, estimatedMinutes: 3 },
    ],
  },
];

export function generateQueueNumber(): string {
  const num = Math.floor(Math.random() * 900) + 100;
  return `A${num}`;
}

export function createMockOrder(
  seafoodId: string,
  estimatedWeight: number,
  processingMethod: string,
  processingFee: number
): Order {
  const steps: ProcessingStepRecord[] = [
    { stepName: "weighing", status: "pending" },
    { stepName: "slaughtering", status: "pending" },
    { stepName: "cooking", status: "pending" },
    { stepName: "packing", status: "pending" },
    { stepName: "pickup", status: "pending" },
  ];

  return {
    id: `ORD-${Date.now()}`,
    seafoodId,
    estimatedWeight,
    estimatedPrice: 0,
    processingMethod,
    processingFee,
    queueNumber: generateQueueNumber(),
    currentStep: "weighing",
    createdAt: new Date().toISOString(),
    status: "pending",
    steps,
  };
}

export const MOCK_ORDERS: Order[] = [
  {
    id: "ORD-001",
    seafoodId: "bolong",
    estimatedWeight: 1.5,
    estimatedPrice: 192,
    actualWeight: 1.6,
    actualPrice: 204.8,
    processingMethod: "蒜蓉",
    processingFee: 10,
    queueNumber: "A101",
    currentStep: "cooking",
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    status: "processing",
    steps: [
      { stepName: "weighing", status: "completed", timestamp: new Date(Date.now() - 1700000).toISOString() },
      { stepName: "slaughtering", status: "completed", timestamp: new Date(Date.now() - 1500000).toISOString() },
      { stepName: "cooking", status: "in_progress", timestamp: new Date(Date.now() - 1200000).toISOString() },
      { stepName: "packing", status: "pending" },
      { stepName: "pickup", status: "pending" },
    ],
  },
  {
    id: "ORD-002",
    seafoodId: "suzicrab",
    estimatedWeight: 0.5,
    estimatedPrice: 34,
    processingMethod: "清蒸",
    processingFee: 0,
    queueNumber: "A102",
    currentStep: "slaughtering",
    createdAt: new Date(Date.now() - 900000).toISOString(),
    status: "processing",
    steps: [
      { stepName: "weighing", status: "completed", timestamp: new Date(Date.now() - 800000).toISOString() },
      { stepName: "slaughtering", status: "in_progress", timestamp: new Date(Date.now() - 600000).toISOString() },
      { stepName: "cooking", status: "pending" },
      { stepName: "packing", status: "pending" },
      { stepName: "pickup", status: "pending" },
    ],
  },
  {
    id: "ORD-003",
    seafoodId: "grouper",
    estimatedWeight: 2.0,
    estimatedPrice: 196,
    actualWeight: 2.3,
    actualPrice: 225.4,
    processingMethod: "清蒸",
    processingFee: 0,
    queueNumber: "A103",
    currentStep: "pickup",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    status: "ready",
    steps: [
      { stepName: "weighing", status: "completed", timestamp: new Date(Date.now() - 3500000).toISOString() },
      { stepName: "slaughtering", status: "completed", timestamp: new Date(Date.now() - 3000000).toISOString() },
      { stepName: "cooking", status: "completed", timestamp: new Date(Date.now() - 2500000).toISOString() },
      { stepName: "packing", status: "completed", timestamp: new Date(Date.now() - 2000000).toISOString() },
      { stepName: "pickup", status: "in_progress", timestamp: new Date(Date.now() - 1800000).toISOString() },
    ],
  },
];
